using Ambev.DeveloperEvaluation.Domain.Entities;
using AutoMapper;

namespace Ambev.DeveloperEvaluation.Application.Sale.UpdateSale
{
    /// <summary>
    /// AutoMapper profile for mapping between UpdateSaleCommand and Sale entity.
    /// </summary>
    /// <remarks>
    /// Maps the command to the domain entity and the updated entity back to the result.
    /// </remarks>
    public class UpdateSaleProfile : Profile
    {
        public UpdateSaleProfile()
        {
            // Date is resolved by the handler (keeps the original date when not informed).
            CreateMap<UpdateSaleCommand, Domain.Entities.Sale>()
                .ForMember(dest => dest.Date, opt => opt.Ignore());

            // Items without Id are new items (Guid.Empty => generated by the database).
            CreateMap<UpdateSaleItemDto, SaleItem>()
                .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id ?? Guid.Empty));
        }
    }
}
